### PR TITLE
Code cleanup

### PR DESCRIPTION
**Pull request by Nachtalb**
Applied some basic pep conventions like spaces between =, 1 newlines for methods 2 for functions, space between comment # and comment. And I removed trailing whitespaces and replaced tabs with spaces for a more consistent code base.

### CODE REVIEW

**Comment by ohld** [comment]
LGTM

**Comment by Nachtalb** [comment]
@ohld 
Could you please take a look at the other PRs too. ATM I am not really sure if this project is actually still actively maintained. If not I will be working on my fork otherwise I will make more PR's here if that is ok.

**Comment by ohld** [comment]
@Nachtalb I'm working on my version of Django telegram bot right now. I'll publish it soon. I decided to host backend (django rest) and frontend (telegram bot) separately. Frontend is just a trigger of backend's endpoints. That architecture will allow connecting multiple telegram bot and bots from other platforms. Follow me on github

**Comment by lukruh** [comment]
@ohld do you have a repository of your version? I'm looking for a solid base to create bots fast and simple from templates. This plugin seems to fit perfect, but It does not look up to date anymore. 

@Nachtalb still working on your fork?

**Comment by Nachtalb** [comment]
@lukruh I stopped working on it after @ohld told me about the his new work. I'll plan to make new bot maybe I'll be working with this base again. If so I'll be expanding my fork further.

**Comment by ohld** [comment]
@Nachtalb @lukruh I've created a template for myself but I have not prepared it to be released as open source software because I would have to create a lot of documentation and stuff. But maybe I'll make it. I am not sure if it will be useful to a lot of people.

Right now I have some problems with concurrency because if I use ConversationalHandler the state should be stored in database also. Otherwise, each thread would have its own state and the bot will go crazy. Right now I am not sure how to code that properly.

**Comment by Nachtalb** [comment]
@ohld why not put it on GitHub and let people help you ;-)

**Comment by alisher-matkurbanov** [comment]
@ohld 
> Right now I have some problems with concurrency because if I use ConversationalHandler the state should be stored in database also. Otherwise, each thread would have its own state and the bot will go crazy. Right now I am not sure how to code that properly.

As you mention above, you decided to split frontend and backend parts. Why not to implement something like RestApiPersistence (based on the ptb BasePersistence interface) that will be send user_data, chat_data and conversation_data by rest api to backend? Backend will store data wherever it want. 
I described this idea [here](https://github.com/python-telegram-bot/python-telegram-bot/issues/1717) but still not find the time to implement it.

Maybe it will help you 🤷🏻‍♂️

**Comment by ohld** [comment]
@alisher-matkurbanov right now I've already combined frontend and backend in one Django project. Django webhook endpoint inserts an incoming message into the python-telegram-bot instance. I just have a regular `bot.py` file in the Django app folder. I think it is a great solution because if we have frontend/backend both of them should be able to send messages through the bot which seems to be wrong.

Anyway, seems like I need just to store in DB the `conversation_data` JSON and insert it after each call of the bot.

**Pull request closed without merging**
